"use client";

import Link from "next/link";
import { ChevronLeft, Link2, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { cognitiveFunctions, type CognitiveFunction, type SafeProviderConfig } from "@/domain/types";
import { Button } from "@/components/ui/button";

const names: Record<CognitiveFunction, string> = { facilitate: "引导", mirror: "镜像", clarify: "澄清", distinguish: "区分", ground: "经验", challenge: "挑战", extend: "延展", connect: "连接", reformulate: "重述", record: "记录" };
type Mapping = { providerId: string; modelId: string };

export default function FunctionsSettingsPage() {
  const [providers, setProviders] = useState<SafeProviderConfig[]>([]); const [mapping, setMapping] = useState<Record<string, Mapping>>({}); const [saved, setSaved] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/providers").then((response) => response.json() as Promise<{ providers: SafeProviderConfig[] }>), fetch("/api/functions").then((response) => response.json() as Promise<{ models: Array<{ cognitiveFunction: string; providerId: string | null; modelId: string | null }> }>)]).then(([providerData, modelData]) => { setProviders(providerData.providers); setMapping(Object.fromEntries(cognitiveFunctions.map((name) => { const model = modelData.models.find((item) => item.cognitiveFunction === name); return [name, { providerId: model?.providerId ?? "", modelId: model?.modelId ?? "" }]; }))); }); }, []);
  async function save() { const response = await fetch("/api/functions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ models: cognitiveFunctions.map((name) => ({ cognitiveFunction: name, providerId: mapping[name]?.providerId || null, modelId: mapping[name]?.modelId || null })) }) }); const data = await response.json() as { error?: string }; setSaved(response.ok ? "认知功能分配已原子保存。未指定时使用默认模型。" : data.error ?? "保存失败"); }
  return <main className="min-h-screen bg-[var(--paper)]"><header className="mx-auto flex max-w-4xl items-center justify-between px-6 py-6"><Link href="/settings/providers" className="flex items-center gap-2 text-sm text-[var(--muted)] hover:text-[var(--ink)]"><ChevronLeft size={16} />模型服务</Link><nav className="flex gap-4 text-xs text-[var(--muted)]"><Link href="/settings/providers">模型服务</Link><Link href="/settings/functions" className="text-[var(--ink)]">认知功能</Link><Link href="/settings/general">常规</Link></nav></header><div className="mx-auto max-w-4xl px-6 pb-20"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--accent)]">设置 / 认知功能</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em]">功能不是人格。</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--muted)]">每项功能可以继承默认模型，也可以指定具体 Provider + Model。保存一次完成全部映射。</p><div className="mt-10 space-y-2">{cognitiveFunctions.map((name) => <div key={name} className="grid gap-3 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-4 sm:grid-cols-[1fr_180px_180px] sm:items-center"><div><p className="text-sm font-semibold">{names[name]}</p><p className="mt-1 text-xs text-[var(--muted)]">{name}</p></div><select aria-label={`${names[name]} Provider`} value={mapping[name]?.providerId ?? ""} onChange={(event) => setMapping({ ...mapping, [name]: { ...(mapping[name] ?? { modelId: "" }), providerId: event.target.value } })} className="rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2 text-xs outline-none"><option value="">继承默认模型</option>{providers.map((provider) => <option key={provider.id} value={provider.id} disabled={!provider.enabled}>{provider.name}{!provider.enabled ? "（已停用）" : ""}</option>)}</select><input aria-label={`${names[name]} Model ID`} value={mapping[name]?.modelId ?? ""} onChange={(event) => setMapping({ ...mapping, [name]: { ...(mapping[name] ?? { providerId: "" }), modelId: event.target.value } })} placeholder="继承 Provider 模型" className="rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2 text-xs outline-none focus:border-[var(--accent)]" /></div>)}</div><div className="mt-6 flex items-center gap-3"><Button variant="primary" onClick={() => void save()}><Save size={14} />保存分配</Button><span className="flex items-center gap-1 text-xs text-[var(--muted)]"><Link2 size={12} />默认每轮只选择一个功能</span>{saved && <span className="text-xs text-[var(--accent)]">{saved}</span>}</div></div></main>;
}
