"use client";

import Link from "next/link";
import { Check, ChevronLeft, KeyRound, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import type { ProviderKind, SafeProviderConfig } from "@/domain/types";
import { Button } from "@/components/ui/button";

const kinds: Array<[ProviderKind, string]> = [["mock", "本地模拟模型"], ["openai", "OpenAI"], ["anthropic", "Anthropic"], ["google", "Google Generative AI"], ["openai-compatible", "OpenAI-compatible"]];

export default function ProvidersSettingsPage() {
  const [providers, setProviders] = useState<SafeProviderConfig[]>([]);
  const [form, setForm] = useState({ name: "我的本地模型", kind: "mock" as ProviderKind, baseUrl: "", apiKey: "", modelId: "demo", isDefault: true });
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/providers", { cache: "no-store" }); if (response.ok) setProviders((await response.json() as { providers: SafeProviderConfig[] }).providers); }
  useEffect(() => {
    let active = true;
    fetch("/api/providers", { cache: "no-store" }).then((response) => response.json() as Promise<{ providers: SafeProviderConfig[] }>).then((data) => { if (active) setProviders(data.providers); }).catch(() => undefined);
    return () => { active = false; };
  }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/providers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, headers: {} }) }); if (response.ok) { setMessage("已保存。API Key 只显示掩码，原文不会返回浏览器。"); setForm({ name: "新的供应商", kind: "mock", baseUrl: "", apiKey: "", modelId: "demo", isDefault: false }); void load(); } else setMessage("保存失败，请检查配置。"); }
  async function remove(id: string) { await fetch("/api/providers?id=" + id, { method: "DELETE" }); void load(); }
  async function test(id: string) { const response = await fetch("/api/providers/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); const data = await response.json() as { message: string }; setMessage(data.message); }
  return <main className="min-h-screen bg-[var(--paper)]">
    <header className="mx-auto flex max-w-5xl items-center justify-between px-6 py-6"><Link href="/app" className="flex items-center gap-2 text-sm text-[var(--muted)] hover:text-[var(--ink)]"><ChevronLeft size={16} />返回工作台</Link><nav className="flex gap-4 text-xs text-[var(--muted)]"><Link href="/settings/providers" className="text-[var(--ink)]">模型服务</Link><Link href="/settings/functions">认知功能</Link><Link href="/settings/general">常规</Link></nav></header>
    <div className="mx-auto max-w-5xl px-6 pb-20"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--accent)]">设置 / 模型服务</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em]">决定谁来帮你照亮一个念头。</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">没有 API Key 时，使用本地模拟模型。真实 Key 只在服务器端读取，并以本地加密方式保存。</p></div>
      <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_340px]"><section className="space-y-3">{providers.length === 0 ? <div className="rounded-2xl border border-dashed border-[var(--line-strong)] p-8 text-sm text-[var(--muted)]">还没有供应商配置。先添加本地模拟模型即可体验完整流程。</div> : providers.map((provider) => <div key={provider.id} className="flex items-center justify-between rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex items-start gap-3"><span className="mt-0.5 flex size-8 items-center justify-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><KeyRound size={15} /></span><div><div className="flex items-center gap-2 text-sm font-semibold">{provider.name}{provider.isDefault && <span className="flex items-center gap-1 rounded-full bg-[var(--accent-soft)] px-2 py-0.5 text-[10px] font-normal text-[var(--accent)]"><Check size={10} />默认</span>}</div><p className="mt-1 text-xs text-[var(--muted)]">{kinds.find(([kind]) => kind === provider.kind)?.[1]} · {provider.modelId ?? "未指定模型"} · {provider.apiKeyMasked}</p></div></div><div className="flex items-center gap-1"><Button size="icon" variant="ghost" onClick={() => void test(provider.id)} aria-label="测试连接"><RefreshCw size={14} /></Button><Button size="icon" variant="ghost" onClick={() => void remove(provider.id)} aria-label="删除供应商"><Trash2 size={14} /></Button></div></div>)}</section>
        <form onSubmit={(event) => void save(event)} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">新增供应商</h2><Plus size={16} className="text-[var(--accent)]" /></div><div className="mt-5 space-y-4"><label className="block text-xs text-[var(--muted)]">显示名称<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="block text-xs text-[var(--muted)]">供应商<select value={form.kind} onChange={(event) => setForm({ ...form, kind: event.target.value as ProviderKind })} className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2.5 text-sm outline-none">{kinds.map(([kind, name]) => <option key={kind} value={kind}>{name}</option>)}</select></label><label className="block text-xs text-[var(--muted)]">Base URL（兼容服务可填）<input value={form.baseUrl} onChange={(event) => setForm({ ...form, baseUrl: event.target.value })} placeholder="https://api.example.com/v1" className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="block text-xs text-[var(--muted)]">API Key<input type="password" value={form.apiKey} onChange={(event) => setForm({ ...form, apiKey: event.target.value })} placeholder="只在服务端保存" className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="block text-xs text-[var(--muted)]">Model ID<input value={form.modelId} onChange={(event) => setForm({ ...form, modelId: event.target.value })} placeholder="例如 gpt-4o-mini" className="mt-1.5 w-full rounded-lg border border-[var(--line)] bg-[var(--surface-raised)] px-3 py-2.5 text-sm outline-none focus:border-[var(--accent)]" /></label><label className="flex items-center gap-2 text-xs text-[var(--ink-soft)]"><input type="checkbox" checked={form.isDefault} onChange={(event) => setForm({ ...form, isDefault: event.target.checked })} />设为默认模型</label><Button type="submit" variant="primary" className="w-full">保存供应商</Button>{message && <p className="text-xs leading-5 text-[var(--accent)]">{message}</p>}</div></form>
      </div>
    </div>
  </main>;
}
